/**
 * @module lib/platform/module-registry/manifests
 * Central registry of module manifests for cap 18 PlatformModuleRegistry.
 *
 * Each module's frontend code declares its manifest here. Backend imports
 * the same shape via the `module_definitions` table seed (spec §5).
 *
 * Adding a new module: append a manifest, run app, system_admin enables
 * for the right orgs in /admin/modules.
 */
import type { ModuleManifest } from "@/lib/modules/module-registry/types";

const MANIFESTS: ModuleManifest[] = [
  {
    key: "helpdesk",
    label: "Helpdesk",
    label_he: "הלפדסק",
    description:
      "Ticket queue, technicians, SLA, approvals, maintenance windows, batch operations.",
    category: "operations",
    icon: "HeadphonesIcon",
    base_route: "/helpdesk",
    nav_entries: [
      { label: "Helpdesk", label_he: "דשבורד הלפדסק", href: "/helpdesk", icon: "HeadphonesIcon", order: 1 },
      { label: "Tickets", label_he: "כרטיסים", href: "/helpdesk/tickets", icon: "ClipboardList", order: 2 },
      { label: "Technicians", label_he: "טכנאים", href: "/helpdesk/technicians", icon: "Users", order: 3 },
      { label: "SLA", label_he: "SLA", href: "/helpdesk/sla", icon: "Activity", order: 4 },
      { label: "Maintenance", label_he: "תחזוקה", href: "/helpdesk/maintenance", icon: "Wrench", order: 5 },
      { label: "Batch tasks", label_he: "משימות אצווה", href: "/helpdesk/batch", icon: "Layers", order: 6 },
      { label: "KB", label_he: "בסיס ידע", href: "/helpdesk/kb", icon: "BookOpen", order: 7 },
    ],
    ai_actions: [
      "helpdesk.ticket.take",
      "helpdesk.ticket.resolve",
      "helpdesk.maintenance.cancel",
      "helpdesk.batch.cancel",
    ],
    permissions: [
      "helpdesk.view",
      "helpdesk.assign",
      "helpdesk.resolve",
      "helpdesk.maintenance.manage",
    ],
    search_types: ["ticket", "kb"],
    introduced_in_version: "0.42.0",
    status: "stable",
    required_flags: ["helpdesk.enabled"],
    required_plans: [],
    conflicts_with: [],
    dashboard_tile: { enabled: true, size: "lg" },
    default_landing: "/helpdesk",
    org_admin_can_toggle: true,
  },
  {
    key: "audit-log",
    label: "Audit Log",
    label_he: "יומן ביקורת",
    description: "Platform-wide activity record. System and AI actions.",
    category: "core",
    icon: "ClipboardList",
    base_route: "/audit-log",
    nav_entries: [
      { label: "Audit log", label_he: "יומן ביקורת", href: "/audit-log", icon: "ClipboardList", order: 1 },
    ],
    ai_actions: [],
    permissions: ["audit.view", "audit.export"],
    search_types: [],
    introduced_in_version: "0.46.0",
    status: "stable",
    required_flags: [],
    required_plans: [],
    conflicts_with: [],
    dashboard_tile: null,
    default_landing: "/audit-log",
    org_admin_can_toggle: false,
  },
  {
    key: "users",
    label: "Users",
    label_he: "משתמשים",
    description: "User management, roles, permissions.",
    category: "core",
    icon: "Users",
    base_route: "/users",
    nav_entries: [
      { label: "Users", label_he: "משתמשים", href: "/users", icon: "Users", order: 1 },
      { label: "Roles", label_he: "תפקידים והרשאות", href: "/roles", icon: "ShieldCheck", order: 2 },
      { label: "Organizations", label_he: "ארגונים", href: "/organizations", icon: "Building2", order: 3 },
    ],
    ai_actions: [],
    permissions: ["users.view", "users.create", "users.edit", "users.delete"],
    search_types: ["user", "org"],
    introduced_in_version: "0.40.0",
    status: "stable",
    required_flags: [],
    required_plans: [],
    conflicts_with: [],
    dashboard_tile: { enabled: true, size: "md" },
    default_landing: "/users",
    org_admin_can_toggle: false,
  },
  {
    key: "ai-agents",
    label: "AI Agents",
    label_he: "סוכני AI",
    description: "Autonomous AI agents — investigations, scheduled runs.",
    category: "ai",
    icon: "Bot",
    base_route: "/ai-agents",
    nav_entries: [
      { label: "AI Agents", label_he: "סוכני AI", href: "/ai-agents", icon: "Bot", order: 1 },
    ],
    ai_actions: [],
    permissions: ["ai_agents.view", "ai_agents.run"],
    search_types: [],
    introduced_in_version: "0.45.0",
    status: "beta",
    required_flags: ["ai_agents.enabled"],
    required_plans: ["pro", "enterprise"],
    conflicts_with: [],
    dashboard_tile: { enabled: true, size: "md" },
    default_landing: "/ai-agents",
    org_admin_can_toggle: true,
  },
  {
    key: "ai-providers",
    label: "AI Providers",
    label_he: "ספקי AI",
    description: "Configure LLM providers — OpenAI, Anthropic, Bedrock, local.",
    category: "ai",
    icon: "Cpu",
    base_route: "/ai-providers",
    nav_entries: [
      { label: "AI Providers", label_he: "ספקי AI", href: "/ai-providers", icon: "Cpu", order: 1 },
    ],
    ai_actions: [],
    permissions: ["ai_providers.view", "ai_providers.configure"],
    search_types: [],
    introduced_in_version: "0.46.0",
    status: "beta",
    required_flags: ["ai_providers.enabled"],
    required_plans: [],
    conflicts_with: [],
    dashboard_tile: null,
    default_landing: "/ai-providers",
    org_admin_can_toggle: true,
  },
  {
    key: "knowledge",
    label: "Knowledge / RAG",
    label_he: "ידע ו-RAG",
    description: "Knowledge base with vector retrieval for AI grounding.",
    category: "ai",
    icon: "Brain",
    base_route: "/knowledge",
    nav_entries: [
      { label: "Knowledge", label_he: "ידע ו-RAG", href: "/knowledge", icon: "Brain", order: 1 },
    ],
    ai_actions: [],
    permissions: ["knowledge.view", "knowledge.write"],
    search_types: ["kb"],
    introduced_in_version: "0.47.0",
    status: "experimental",
    required_flags: ["knowledge.enabled"],
    required_plans: ["pro", "enterprise"],
    conflicts_with: [],
    dashboard_tile: null,
    default_landing: "/knowledge",
    org_admin_can_toggle: true,
  },
  {
    key: "voice",
    label: "Voice Agent",
    label_he: "ALA — Voice AI",
    description: "Phone-based AI agent for inbound support.",
    category: "ai",
    icon: "Mic",
    base_route: "/ala",
    nav_entries: [
      { label: "ALA — Voice AI", label_he: "ALA — Voice AI", href: "/ala", icon: "Mic", order: 1 },
      { label: "Voice calls", label_he: "שיחות קוליות", href: "/voice", icon: "Phone", order: 2 },
    ],
    ai_actions: [],
    permissions: ["voice.view", "voice.configure"],
    search_types: [],
    introduced_in_version: "0.50.0",
    status: "experimental",
    required_flags: ["voice_agent.enabled"],
    required_plans: ["enterprise"],
    conflicts_with: [],
    dashboard_tile: null,
    default_landing: "/ala",
    org_admin_can_toggle: true,
  },
  {
    key: "automation",
    label: "Automation",
    label_he: "אוטומציה",
    description: "Workflow automation — triggers, actions, schedules.",
    category: "operations",
    icon: "Zap",
    base_route: "/automation",
    nav_entries: [
      { label: "Automation", label_he: "אוטומציה", href: "/automation", icon: "Zap", order: 1 },
    ],
    ai_actions: [],
    permissions: ["automation.view", "automation.run"],
    search_types: [],
    introduced_in_version: "0.48.0",
    status: "experimental",
    required_flags: [],
    required_plans: ["pro", "enterprise"],
    conflicts_with: [],
    dashboard_tile: null,
    default_landing: "/automation",
    org_admin_can_toggle: true,
  },
  {
    key: "integrations",
    label: "Integrations",
    label_he: "אינטגרציות",
    description: "Third-party app connectors — Slack, GitHub, Jira.",
    category: "operations",
    icon: "Puzzle",
    base_route: "/integrations",
    nav_entries: [
      { label: "Integrations", label_he: "אינטגרציות", href: "/integrations", icon: "Puzzle", order: 1 },
    ],
    ai_actions: [],
    permissions: ["integrations.view", "integrations.configure"],
    search_types: [],
    introduced_in_version: "0.43.0",
    status: "beta",
    required_flags: ["integrations.enabled"],
    required_plans: [],
    conflicts_with: [],
    dashboard_tile: null,
    default_landing: "/integrations",
    org_admin_can_toggle: true,
  },
  {
    key: "monitoring",
    label: "Monitoring",
    label_he: "ניטור",
    description: "System health, logs, metrics.",
    category: "core",
    icon: "Network",
    base_route: "/monitoring",
    nav_entries: [
      { label: "Health", label_he: "בריאות המערכת", href: "/monitoring", icon: "Network", order: 1 },
      { label: "Logs", label_he: "לוגים", href: "/logs", icon: "FileText", order: 2 },
      { label: "Metrics", label_he: "מטריקות", href: "/metrics", icon: "BarChart2", order: 3 },
    ],
    ai_actions: [],
    permissions: ["monitoring.view"],
    search_types: [],
    introduced_in_version: "0.41.0",
    status: "stable",
    required_flags: [],
    required_plans: [],
    conflicts_with: [],
    dashboard_tile: { enabled: true, size: "md" },
    default_landing: "/monitoring",
    org_admin_can_toggle: false,
  },
  {
    key: "billing",
    label: "Billing",
    label_he: "חיוב",
    description: "Subscription, invoices, usage meter, API keys.",
    category: "growth",
    icon: "CreditCard",
    base_route: "/billing",
    nav_entries: [
      { label: "Billing", label_he: "חיוב", href: "/billing", icon: "CreditCard", order: 1 },
      { label: "API keys", label_he: "מפתחות API", href: "/api-keys", icon: "KeyRound", order: 2 },
    ],
    ai_actions: [],
    permissions: ["billing.view", "billing.manage"],
    search_types: [],
    introduced_in_version: "0.49.0",
    status: "experimental",
    required_flags: [],
    required_plans: [],
    conflicts_with: [],
    dashboard_tile: null,
    default_landing: "/billing",
    org_admin_can_toggle: false,
  },
  {
    key: "data-sources",
    label: "Data Sources",
    label_he: "מקורות נתונים",
    description: "Generic data-source connectors — databases, files, APIs.",
    category: "operations",
    icon: "HardDrive",
    base_route: "/data-sources",
    nav_entries: [
      { label: "Data sources", label_he: "מקורות נתונים", href: "/data-sources", icon: "HardDrive", order: 1 },
    ],
    ai_actions: [],
    permissions: ["data_sources.view", "data_sources.configure"],
    search_types: [],
    introduced_in_version: "0.43.0",
    status: "experimental",
    required_flags: ["data_sources.enabled"],
    required_plans: ["pro", "enterprise"],
    conflicts_with: [],
    dashboard_tile: null,
    default_landing: "/data-sources",
    org_admin_can_toggle: true,
  },
];

export function getAllManifests(): ModuleManifest[] {
  return MANIFESTS;
}

export function getManifest(key: string): ModuleManifest | undefined {
  return MANIFESTS.find((m) => m.key === key);
}
